app:
    es:
        conf:
            - name: dev
              addresses:
                - http://192.168.1.231:9200
              username: "elastic"
              password: "123456"
    port: 8081
