info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 首页
      tags:
      - 首页
  /conf/add:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 添加es配置
      tags:
      - es配置
  /conf/del:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 删除es配置
      tags:
      - es配置
  /conf/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 获取es配置
      tags:
      - es配置
  /conf/use:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 设置es配置
      tags:
      - es配置
  /es/getIndices:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 获取es索引
      tags:
      - es查询
  /es/getMappings:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
      summary: 获取es索引mappings
      tags:
      - es查询
swagger: "2.0"
